/ros2_bag_recorder_node:
  ros__parameters:
    topics_info: 
      topic_names: ["/chatter", "/cmd_vel"]
      message_types: ["std_msgs.msg", "geometry_msgs.msg"]
      data_types: ["String", "Twist"]
      interface_types: ["std_msgs/msg/String", "geometry_msgs/msg/Twist"]
      callback_function: ["chatterCallback", "cmdVelCallback"]
      queue_sizes: [10, 10]
      variable_names: ["chatter_message", "cmd_vel_message"]

    # [["/chatter", "std_msgs.msg", "String", "chatterCallback", "10", "chatter_message"], ["/talker", "std_msgs.msg", "String", "chatterCallback", "10", "chatter_message"]] 

    bag_file_direction: "/home/furkan/colcon_ws_galactic_outdoor/src/ros2_bag_save/bags/" 